steps:
# Print the file content to verify
- name: 'ubuntu'
  args: ['cat', 'src/api/main.py']

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/rag-api', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/rag-api']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'rag-api'
  - '--image'
  - 'gcr.io/$PROJECT_ID/rag-api'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '2Gi'
  - '--timeout'
  - '300'
  - '--set-env-vars'
  - 'STORAGE_BUCKET=rag-application-455020-rag-vector-store,MODEL_NAME=gpt-3.5-turbo,USE_COMPRESSION=true,RETRIEVAL_TOP_K=5,TEMPERATURE=0.1'
  - '--set-secrets'
  - 'OPENAI_API_KEY=openai-api-key:latest'

images:
- 'gcr.io/$PROJECT_ID/rag-api'